# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bc28623c1bb9ea804d06944c35dbb2a60a6a72b6bf101229828fdca7ccabd186eb4b509406b585c8b4e95c60aa55fe3f38b717505b02693898b7ed3a087d745

test:
  secret_key_base: 9d75091b1de5197d2669014f2ecc28228ba650f54f87cc9df8641f684a88f620d46158a34e511095129bc459065a5672111c7a7c3d3afc9a4250f6ecce6f8590

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
